### ISSUE TITLE
Binding to an <a> without content does not work

### ISSUE THREAD

**Issue by gmassanek** [EndangeredMassa/facile.js#10]
``` ruby

:twitter_share => {
  :href => 'http://twitter.com/share',
  :'data-tweet-text' => 'Some text here'
}
```

does not bind to  `%a.twitter_share` properly. Neither href or the data attribute make it to the markup. It only works when you include a `:content` key

**Comment by EndangeredMassa** [comment]
This is expected behavior. I wouldn't mind doing this a better way; I just don't know what that would be.

Right now, you have to use `content` to trigger the attribute mapping. Otherwise, we can't know if those are attributes on an object or more key-value-pairs to map to other objects.

One thing we could do is to treat the binding data as a real hierarchical structure where we look for keys and, if not found, assume they are attributes. I'd be afraid of overbinding, though. What if someone wants to bind a large object to their data because they don't want to bother trimming it down first.
